version: "3"
services:
    db:
        image: "mcr.microsoft.com/mssql/server"
        environment:
            SA_PASSWORD: "MySuperRandomStrong!Passw0rd!"
            ACCEPT_EULA: "Y"
        ports:
            - "1433:1433"
            
    web:
        build: .
        ports:
            - "8000:5000"
        depends_on:
            - db